# output for command: /apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/bin/python -m pip install --prefix=/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .

Processing /tmp/vsc43810/easybuild/build/scibpipeline/0.2.0/foss-2022a/anndata2ri/anndata2ri-1.1
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
   Preparing metadata (pyproject.toml) did not run successfully.
   exit code: 1
  > [38 lines of output]
      Traceback (most recent call last):
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/metadata/core.py", line 1227, in cached
          self._cached = self.source.get_version_data()['version']
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/metadata/core.py", line 1273, in source
          raise UnknownPluginError(f'Unknown version source: {source_name}')
      hatchling.plugin.exceptions.UnknownPluginError: Unknown version source: vcs
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/apps/gent/RHEL8/haswell-ib/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/build.py", line 41, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 80, in build
          self.metadata.validate_fields()
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/metadata/core.py", line 168, in validate_fields
          _ = self.version
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/metadata/core.py", line 55, in version
          self._set_version()
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/metadata/core.py", line 150, in _set_version
          version = self.hatch.version.cached
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/metadata/core.py", line 1229, in cached
          raise type(e)(f'Error getting the version from source `{self.source.PLUGIN_NAME}`: {e}') from None
        File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/lib/python3.10/site-packages/hatchling/metadata/core.py", line 1273, in source
          raise UnknownPluginError(f'Unknown version source: {source_name}')
      hatchling.plugin.exceptions.UnknownPluginError: Unknown version source: vcs
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

 Encountered error while generating package metadata.
> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
